CREATE ROLE dbz_user WITH LOGIN REPLICATION PASSWORD 'dbz_user';

GRANT CONNECT ON DATABASE restaurant_db to dbz_user;
GRANT USAGE ON SCHEMA public TO dbz_user;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO dbz_user;

ALTER DEFAULT PRIVILEGES FOR USER root IN SCHEMA public
GRANT SELECT ON TABLES TO dbz_user;

CREATE PUBLICATION dbz_publication FOR ALL TABLES;