create table customers (
    customer_id bigint generated by default as identity primary key,
    name text,
    birthday date,
    city text,
    phone text,
    customer_segment text,
    registration_date timestamp default now(),
    updated_at timestamp not null default now()
);

create table branches (
    branch_id bigint generated by default as identity primary key,
    name text,
    city text,
    address text,
    phone text,
    status text,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create table payments (
    payment_id bigint generated by default as identity primary key,
    payment_type name,
    bank_name text,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);


create table categories (
    category_id bigint generated by default as identity primary key,
    name text,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now()
);

create table products (
    product_id bigint generated by default as identity primary key,
    product_name text,
    price numeric(10,0),
    cost numeric(10,0),
    category_id bigint,
    created_at timestamp not null default now(),
    updated_at timestamp not null default now(),

    constraint fk_products_categories
        foreign key (category_id)
        references categories(category_id)
);

create table orders (
    order_id bigint generated by default as identity primary key,
    customer_id bigint,
    branch_id bigint,
    payment_id bigint,
    total_amount numeric(12,0),
    created_at timestamp not null default now(),
    completed_at timestamp,
    canceled_at timestamp,
    status text,

    constraint fk_orders_customers 
        foreign key (customer_id)
        references customers(customer_id),
    
    constraint fk_orders_branches
        foreign key (branch_id)
        references branches(branch_id),

    constraint fk_orders_payments
        foreign key (payment_id)
        references payments(payment_id)
);

create table order_items (
    order_items_id bigint generated by default as identity primary key,
    order_id bigint,
    product_id bigint,
    quantity integer,
    unit_price numeric(10,0),
    unit_cost numeric(10,0),
    created_at timestamp not null,

    constraint fk_order_items_orders
        foreign key (order_id)
        references orders(order_id),
    
    constraint fk_order_items_products
        foreign key (product_id)
        references products(product_id)
);


